### ISSUE TITLE
Calling `eleventyConfig.addPlugin` without a config object results in errors

### ISSUE THREAD

**Issue by grempe** [gfscott/eleventy-plugin-embed-twitter#2]
OK

```javascript
eleventyConfig.addPlugin(embedTwitter, {
  cacheText: false,
})
```

OK

```javascript
eleventyConfig.addPlugin(embedTwitter, {})
```

FAILS (This is what's shown in the README)

```javascript
eleventyConfig.addPlugin(embedTwitter)
```

Error output:

```
❯ npm start

> @ start REDACTED
> ELEVENTY_ENV=development eleventy --serve & postcss styles/tailwind.css --o _tmp/style.css --watch

Unhandled rejection in promise ([object Promise]): (more in DEBUG output)
> Cannot convert undefined or null to object

`TypeError` was thrown:
    TypeError: Cannot convert undefined or null to object
        at Function.keys (<anonymous>)
        at getKeys (/Users/glenn/src/github.com/REDACTED-www-tailwind/node_modules/deepmerge/dist/cjs.js:61:16)
        at mergeObject (/Users/glenn/src/github.com/REDACTED-www-tailwind/node_modules/deepmerge/dist/cjs.js:86:2)
        at deepmerge (/Users/glenn/src/github.com/REDACTED-www-tailwind/node_modules/deepmerge/dist/cjs.js:117:10)
        at module.exports (/Users/glenn/src/github.com/REDACTED-www-tailwind/node_modules/eleventy-plugin-embed-twitter/.eleventy.js:8:23)
        at UserConfig.addPlugin (/Users/glenn/src/github.com/REDACTED-www-tailwind/node_modules/@11ty/eleventy/src/UserConfig.js:273:7)
        at module.exports (/Users/glenn/src/github.com/REDACTED-www-tailwind/.eleventy.js:50:18)
        at TemplateConfig.mergeConfig (/Users/glenn/src/github.com/REDACTED-www-tailwind/node_modules/@11ty/eleventy/src/TemplateConfig.js:91:25)
        at new TemplateConfig (/Users/glenn/src/github.com/REDACTED-www-tailwind/node_modules/@11ty/eleventy/src/TemplateConfig.js:25:24)
        at Object.<anonymous> (/Users/glenn/src/github.com/REDACTED-www-tailwind/node_modules/@11ty/eleventy/src/Config.js:5:14)

warn - You have enabled experimental features: extendedSpacingScale, defaultLineHeights, extendedFontSizeScale
warn - Experimental features are not covered by semver, may introduce breaking changes, and can change at any time.

risk - There are upcoming breaking changes: purgeLayersByDefault
risk - We highly recommend opting-in to these changes now to simplify upgrading Tailwind in the future.
risk - https://tailwindcss.com/docs/upcoming-changes

REDACTED

Benchmark (Configuration): "svgContents" Nunjucks Filter took 461ms (21.5%, called 1602×, 0.3ms each)
Copied 465 files / Wrote 53 files in 1.91 seconds (36.0ms each, v0.11.0)
Watching…
[Browsersync] Access URLs:
 -------------------------------------
       Local: http://localhost:8080
    External: http://10.147.20.71:8080
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://localhost:3001
 -------------------------------------
[Browsersync] Serving files from: _site
File changed: _tmp/style.css
File changed: _tmp/style.css


REDACTED

[Browsersync] Reloading files that match: *.css
Benchmark (Configuration): "svgContents" Nunjucks Filter took 266ms (21.5%, called 1602×, 0.2ms each)
Copied 465 files / Wrote 53 files in 1.23 seconds (23.2ms each, v0.11.0)
Watching…
[Browsersync] Reloading files that match: *.css
```

**Comment by gfscott** [comment]
@grempe Thanks so much for filing this issue! I gave you a shout-out in [the release note](https://github.com/gfscott/eleventy-plugin-embed-twitter/releases), this was a real whopper 😅

**Comment by grempe** [comment]
Awesome. Thanks for resolving so quickly!
